### ISSUE TITLE
P3 To-Do List via Assignment Handout

### ISSUE THREAD

**Issue by lujorryn** [lujorryn/PetPal-G0346#29]
Documentation (5 marks)
- [x] Well written INSTALL document

Deployment (5 marks)
- [x] Website is publicly hosted

Core Features (120 marks)
- -1 mark for aesthetic issues, similar to P1.
- -1 mark for responsive design issues, similar to P1.
- -1 mark for lack of proper error handling. For example, the user should always know what the problem is, such as username already taken, no permission to view a page (or you can just 404 here), etc.
- [x] 404 Page [1 mark]
    - Have a page for 404 page not found.
- [x] Landing [1 mark]
    - This could be a splash page or the main search page. Assume the client will always start navigating your website from the root URL.
- [x] Accounts [29 marks]
    - [x] Login [2 marks]
    - [x] Register [6 marks]
        - [x] Shelter and Seeker
    - [x] List Shelter [4 marks]
        - [x] Pagination support [2 marks]
    - [x] Detail (Seeker) [3 marks]
    - [x] Detail (Shelter) [5 marks]
    - [x] Update [6 marks]
    - [x] Delete [1 mark]
- [x] Pet Listings [30 marks]
    - [x] Create [5 marks]
    - [x] Detail [5 marks]
    - [x] Update [5 marks]
    - [x] List [15 marks]
        - [x] Pagination support [2 marks]
        - [x] Search parameter support [4 marks]
        - [x] 4 Filters (same as P2) [4 marks]
        - [x] 2 Sort by (same as P2) [2 marks]
        - Basic look and feel [3 mark]
- [x] Applications [22 marks]
    - [x] Create [5 marks]
    - [x] Detail [5 marks]
    - [x] Update [1 mark]
    - [x] List [11 marks]
        - [x] Pagination support [2 marks]
        - [x] Search parameter support [4 marks]
        - [x] Filter by status [1 mark]
        - [x] 2 sorts (same as P2) [2 marks]
        - [x] Shelter view [1 mark] Should see all applications for a shelter
        - [x] Seeker view [1 mark] Should see all applications for a seeker.
- [x] Comments [19 marks]
    - [x] Create (for application) [4 marks]
    - [x] Create (for shelter) [5 marks]
    - [x] With rating system support [1 mark]
    - Basic look and feel [4 marks]
    - [x] List (for application and shelter) [10 marks] = Message Center
        - [x] Pagination support [2x2 marks]
        - Basic look and feel [3x2 marks]
- [x] Notifications [18 marks]
    - [x] List [7 marks]
        - [x] Pagination support [2 marks]
        - [x] Filter by status [2 marks]
        - Basic look and feel [3 marks]
    - [x] Detail [8 marks] Can be merged with List
        - Basic look and feel [3 mark]
        - [x] Link to other pages should work
            - [x] To application [2 marks]: Seeker and shelter
            - [x] To shelter [1 mark]: Shelter
            - [x] To pet listing [2 marks]: Seeker only, Based on user preference
    - [x] Update [2 marks]
    - [x] Delete [1 mark]

Extra Feature: Blog (50 marks)
- [x] Backend
- [x] List
- [x] Detail
- [x] Create
- [x] Edit
- [x] Delete
