### ISSUE TITLE
P2 Master To-do List via Assignment Handout

### ISSUE THREAD

**Issue by lujorryn** [lujorryn/PetPal-G0346#4]
- [x] Scripts and Files
  - [x] startup.sh
  - [x] run.sh
  - [x] docs.pdf (README.md)
  
- [x] General Pitfall Checks
  - [x] -1 mark per improper or lack of error handling, e.g., invalid email address, password mismatch, etc.
  - [x] -1 mark per incorrect permission, e.g., shelter A cannot withdraw the pet listings of shelter B, pet seeker A cannot see pet seeker B's adoption applications, etc
  - [x] -1 mark per violation of the REST API, specifically this rule: "Use nouns instead of verbs in endpoint paths".
  - [x] -1 mark for missing information in a model, e.g., no support for user avatar.
  
- [x] Accounts (18 marks) accounts/shelters/seekers apps
  - [x] Authentication (2 marks)
      - [x] Token based authentication (1 mark) 
      - [x] Login (1 mark)
  - [x] Model (3 marks)
      - [x] Shelter and Pet Seeker (You can combine the two account type if you want.)
  - [x] Create/Update (6 marks)
      - [x] Shelter account (3 marks)
      - [x] Pet seeker account (3 marks)
  - [x] Get (4 marks)
      - [x] Any user (shelter or seeker) can see the profile of a shelter.
      - [x] Shelters can only view pet seekers' profiles if they have an active application with the shelter.
  - [x] List (2 marks)
      - [x] Can view a list of shelters
      - [x] Cannot view a list of pet seekers
  - [x] Delete (1 mark)
      - [x] Shelter: all of their pet listings will be deleted.
      - [x] Seeker: all of their applications will be deleted.
      - [x] Both: all of their notifications will be deleted.
  
- [x] Pet Listings (21 marks) 
  - [x] Model (2 marks)
  - [x] Create (3 marks)
  - [x] Update (3 marks)
  - [x] Delete (1 mark)
      - Note that associated applications and their comments will all be deleted as a result.
  - [x] Get (2 marks)
      - [x] All pet listings can be viewed, regardless of status, unless they are deleted.
  - [x] Search Results (10 marks)
      - [x] Must support at least 4 filters. e.g., shelter, status, breed, age, size, color, and gender. (6 marks)
          - [x] Must support filter by shelter and status. The rest is your choice.
          - [x] Default status filter should be "available".
      - [x] Must support at least 2 sorting options, e.g., name, age, and size. (date_posted is also an option) (3 marks)
      - [x] Pagination support (1 mark)
  
- [x] Comments (17 marks) <- check this off if auto-create notif is working
  - You do not need to support updating or deleting a comment.
  - [x] Model (3 marks)
      - [x] Note that users can create comments for reviewing shelters and following up on submitted applications.
      - If comment API is split into two, then marks are also split between the two (same for all other criteria below).
  - [x] Create (6 marks)
      - [x] Only the specific shelter and pet seeker can comment on their application.
      - [x] Any logged in user/shelter can comment on a shelter.
  - [x] List (8 marks)
      - [x] Basic functionality (4 marks)
          - [x] Only the specific shelter and pet seeker can see the comments for their application.
          - [x] Any logged in user/shelter can see comments for a shelter.
      - [x] Sort comments by creation time in descending order. (2 marks)
      - [x] Pagination support (2 marks)
  
- [x] Applications (18 marks)
  - [x] Deleting an application is not allowed (unless it was deleted as a part of deleting its associated pet listing)
  - [x] Model (2 marks) 
  - [x] Create (4 marks)
      - [x] Can only create applications for a pet listing that is "available"
  - [x] Update (3 marks)
      - [x] Details of an application cannot be updated once submitted/created, except for its status (see below).
      - [x] Shelter can only update the status of an application from pending to accepted or denied.
      - [x] Pet seeker can only update the status of an application from pending or accepted to withdrawn.
  - [x] List (7 marks)
      - [x] Shelters can only view their own applications, not that of other shelters.
      - [x] Filter applications by status (2 marks)
      - [x] Sort application by creation time and last update time (4 marks)
          - [x] When an application receives a new comment, its "last update time" should be changed.
      - [x] Pagination support (1 mark)
  - [x] Get (2 marks)
  
- [x] Notifications (16 marks)
  - [x] Model (2 marks) 
  - [x] Create (3 marks)
      - No need to update a notification.
      - Note that you do not have to provide this endpoint IF your other actions will create notification objects directly.
          - E.g., notification created as part of creating a new comment for a shelter.
  - [x] List (6 marks)
      - [x] Users (shelter and seeker) can only view their own notifications (1 mark)
      - [x] Sort notifications by creation time (2 mark)
      - [x] Filter notifications by read/unread (2 mark)
      - [x] Pagination support (1 mark)
  - [x] Delete (1 mark)
  - [x] Get (4 mark)
      - [x] Should provide a link to the associated model
      - [x] Link to new comment added (2 marks)
      - [x] Link to application creation and status update (2 marks)
